name: aleks-bot
version: "3.8"

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aleks-bot
    restart: always
    env_file:
      - .env
    depends_on: 
      - postgre
    networks:
      - aleks-net
  
  postgre:
    image: postgres:latest
    container_name: aleks-postgre
    restart: always
    environment:
      POSTGRES_USER: aleks
      POSTGRES_PASSWORD: aleks
      POSTGRES_DB: aleks
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    networks:
      - aleks-net
    
networks:
  aleks-net:
    driver: bridge