services:
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    restart: always
    networks:
      - default
    volumes:
      - ./bot:/app

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    networks:
      - default
    volumes:
      - ./data:/data

networks:
  default:
    driver: bridge
