services:
  bot:
    build: 
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - "7654:8080"
    volumes:
      - ".:/app"
    environment:
      - "DISCORD_TOKEN=${BOT_TOKEN}"
      - "GUILD_ID=${GUILD_ID:-939861494869426247}"